### ISSUE TITLE
UnknownFieldException: An unknown field for index -3 when XML file starts with <?xml version="1.0" encoding="UTF-8"?>

### ISSUE THREAD

**Issue by frankkienl** [rharter/kotlinx-serialization-xml#55]
When running the example, as written in the README, all is fine.
But when the XML starts with `<?xml version="1.0" encoding="UTF-8"?>`,
the same code fails with `UnknownFieldException: An unknown field for index -3`

Below is the full code to reproduce, using unit testing.

```
@file:OptIn(ExperimentalSerializationApi::class)

package nl.frankkie.fakegps.gpx

import com.ryanharter.kotlinx.serialization.xml.Xml
import com.ryanharter.kotlinx.serialization.xml.XmlAttribute
import com.ryanharter.kotlinx.serialization.xml.XmlContent
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import org.junit.Test

@Serializable
data class Greeting(
    @XmlAttribute val from: String,
    @XmlAttribute val to: String,
    val message: Message
)

@Serializable
data class Message(
    @XmlContent val content: String
)


class DemoXmlParser {
    @Test
    fun testXmlParser1() {
        val xml1 = """
      <Greeting from="Ryan" to="Bill">
        <message>Hi</message>
      </Greeting>
    """.trimIndent()
        val actual = Xml.Default.decodeFromString<Greeting>(xml1)
    }

    @Test
    fun testXmlParser2() {
        val xml2 = """
            <?xml version="1.0" encoding="UTF-8"?>
      <Greeting from="Ryan" to="Bill">
        <message>Hi</message>
      </Greeting>
    """.trimIndent()
        val actual = Xml.Default.decodeFromString<Greeting>(xml2)
    }
}
```

The library should fail gracefully, 
and not require the developer to first filter out the `<?xml version="1.0" encoding="UTF-8"?>` before parsing.

Full output of running this:
```
06-09 15:37:51.148  6586  6607 I TestRunner: started: testXmlParser2(nl.frankkie.fakegps.gpx.DemoXmlParser)
06-09 15:37:51.153  6586  6607 E TestRunner: failed: testXmlParser2(nl.frankkie.fakegps.gpx.DemoXmlParser)
06-09 15:37:51.153  6586  6607 E TestRunner: ----- begin exception -----
06-09 15:37:51.154  6586  6607 E TestRunner: kotlinx.serialization.UnknownFieldException: An unknown field for index -3
06-09 15:37:51.154  6586  6607 E TestRunner: 	at nl.frankkie.fakegps.gpx.Greeting$$serializer.deserialize(DemoXmlParser.kt:14)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at nl.frankkie.fakegps.gpx.Greeting$$serializer.deserialize(DemoXmlParser.kt:14)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at com.ryanharter.kotlinx.serialization.xml.XmlDecoder$DefaultImpls.decodeSerializableValue(XmlDecoder.kt:5)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at com.ryanharter.kotlinx.serialization.xml.internal.StreamingXmlDecoder.decodeSerializableValue(StreamingXmlDecoder.kt:203)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at com.ryanharter.kotlinx.serialization.xml.Xml.decodeFromString(Xml.kt:34)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at nl.frankkie.fakegps.gpx.DemoXmlParser.testXmlParser2(DemoXmlParser.kt:52)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
06-09 15:37:51.154  6586  6607 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2402)
06-09 15:37:51.154  6586  6607 E TestRunner: ----- end exception -----
06-09 15:37:51.155  6586  6607 I TestRunner: finished: testXmlParser2(nl.frankkie.fakegps.gpx.DemoXmlParser)

kotlinx.serialization.UnknownFieldException: An unknown field for index -3
at nl.frankkie.fakegps.gpx.Greeting$$serializer.deserialize(DemoXmlParser.kt:14)
at nl.frankkie.fakegps.gpx.Greeting$$serializer.deserialize(DemoXmlParser.kt:14)
at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
at com.ryanharter.kotlinx.serialization.xml.XmlDecoder$DefaultImpls.decodeSerializableValue(XmlDecoder.kt:5)
at com.ryanharter.kotlinx.serialization.xml.internal.StreamingXmlDecoder.decodeSerializableValue(StreamingXmlDecoder.kt:203)
at com.ryanharter.kotlinx.serialization.xml.Xml.decodeFromString(Xml.kt:34)
at nl.frankkie.fakegps.gpx.DemoXmlParser.testXmlParser2(DemoXmlParser.kt:52)
```

**Comment by rharter** [comment]
Hmm, that's interesting, because there's even [a test for that](https://github.com/rharter/kotlinx-serialization-xml/blob/main/src/commonTest/kotlin/com/ryanharter/kotlinx/serialization/xml/XmlDecoderTest.kt#L216-L232). I notice that your test string has some extra white space before the XML declaration, which I think is breaking the decoder [here](https://github.com/rharter/kotlinx-serialization-xml/blob/998fef95d53942741f922451f438e13eb80be111/src/commonMain/kotlin/com/ryanharter/kotlinx/serialization/xml/internal/StreamingXmlDecoder.kt#L48-L53). 

While my read of the [XML spec](https://www.w3.org/TR/xml/#NT-XMLDecl) suggests that white space before the prolog is invalid, I'm sure it's not uncommon, so I'd expect that the `XmlElementDecoder` just needs a `lexer.skipWhitespace()` before that conditional check. If you want to submit a PR with that check I'd be happy to merge it in.

**Comment by frankkienl** [comment]
PR submitted ;-) !
